enum Flag {
  SOCIAL_MEDIA = "SOCIAL_MEDIA",
  STREAMING_SERVICE = "STREAMING_SERVICE",
  ONLINE_SHOPPING = "ONLINE_SHOPPING",
  FINANCE = "FINANCE",
  WORK = "WORK",
  GAMING = "GAMING",
}

export default Flag;
