openapi: 3.0.0
info:
  title: Backend API
  version: 1.0.0
  description: API for the backend services

servers:
  - url: http://localhost:2198/api/
paths:
  /health:
    get:
      summary: Check health status
      description: Returns the health status of the API
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    nullable: true
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    nullable: true
 